# Generated by Django 4.1.7 on 2023-03-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
