# Generated by Django 4.1.7 on 2023-04-01 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_form_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=8)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='form_contato',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
