# Generated by Django 4.1.7 on 2023-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_login_admin_alter_form_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='visao_geral',
            field=models.TextField(blank=True, null=True),
        ),
    ]
