# Generated by Django 4.1.7 on 2023-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_produto_video_produto_visao_geral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imagemProd',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_Carrossel1',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_Carrossel2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_Carrossel3',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
